### ISSUE TITLE
I see a one pixel top panel on my Fedora

### ISSUE THREAD

**Issue by risbac** [fthx/panel-free#5]
Hello !

I see a one pixel top panel when I use the extension. Is that expected ? I'm using the extension to prevent a burn in on my Oled display, so even this one pixel bar may result in a burn in, sorry if I'm demanding :) Is there any way to fix that in your opinion ? Thanks !

**Comment by risbac** [comment]
Fedora 39 on Wayland to be a bit more precise.

**Comment by fthx** [comment]
I look at this, I do run an updated version I did write but this 1 px is absolutely not expected.
It was in a previous version, to preserve hot corner and some access to panel.

Simply hiding the panel causes issues but I got another idea I did use in one of my other extensions.
I do not use this one atm because I use mainly a 27" monitor.  ;-)

Je te donne le retour du test d'ici qq minutes mais si mon idée ne fonctionne pas, je sèche (la hauteur du panel est réglée à 0, donc mystère !!).

**Comment by risbac** [comment]
Cool ! Comment je peux vérifier si j'ai la bonne version de l'extension ?
Je vais voir si je trouve le numéro de la version une fois chez moi.

**Comment by fthx** [comment]
Voilà.
https://github.com/fthx/panel-free/commit/286be40c359583a2e4964c41c8d44ba8a0efb033
Tu as le nouveau code ici ou très bientôt via màj de l'extension.
N'utilise pas metadata.json (version réglée sur 999 pour éviter les màj sur mon pc).

The trick is not to do Main.panel.hide() but set Main.panel.visible = false .
There are no errors following this way.

**Comment by Aman9das** [comment]
Lovely! the desktop feels SO much snappier too

**Comment by risbac** [comment]
Indeed, no more 1 pixel band, it's pixel perfect !
I guess that the trade off is that the hot corner is not working anymore, right?

**Comment by risbac** [comment]
And just to let you know, this extension seems to enable the top left hot corner again if you set it with the usual behavior : 

https://extensions.gnome.org/extension/4167/custom-hot-corners-extended/

Quite cool !
